services:
  - type: web
    name: mesa-certa
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: bash build.sh
    startCommand: .venv/bin/flask db upgrade && .venv/bin/gunicorn --worker-class sync --workers 1 --timeout 60 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
