services:
  - type: web
    name: mesa-certa
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
