"""add indexes, soft delete, favorito, constraints

Revision ID: 6c3518848aff
Revises: b5a7b14cbacf
Create Date: 2026-05-13 19:48:52.529924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3518848aff'
down_revision = 'b5a7b14cbacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'restaurante_id', name='uq_favorito_usuario_rest')
    )
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_avaliacao_usuario_rest', ['usuario_id', 'restaurante_id'])

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_restaurante_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurante_faixa_preco'), ['faixa_preco'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurante_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurante_nome'))
        batch_op.drop_index(batch_op.f('ix_restaurante_faixa_preco'))
        batch_op.drop_index(batch_op.f('ix_restaurante_categoria'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.drop_constraint('uq_avaliacao_usuario_rest', type_='unique')

    op.drop_table('favorito')
    # ### end Alembic commands ###
