"""initial schema

Revision ID: b5a7b14cbacf
Revises:
Create Date: 2026-05-10 21:43:05.661168

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5a7b14cbacf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("categoria", sa.String(length=80), nullable=False),
        sa.Column("faixa_preco", sa.String(length=30), nullable=False),
        sa.Column("endereco", sa.String(length=200), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("senha_hash", sa.String(length=256), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "avaliacao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("restaurante_id", sa.Integer(), nullable=False),
        sa.Column("nota_atendimento", sa.Integer(), nullable=False),
        sa.Column("nota_ambiente", sa.Integer(), nullable=False),
        sa.Column("nota_prato", sa.Integer(), nullable=False),
        sa.Column("nota_preco", sa.Integer(), nullable=False),
        sa.Column("media_calculada", sa.Float(), nullable=True),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column("foto_path", sa.String(length=256), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["restaurante_id"],
            ["restaurante.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("avaliacao")
    op.drop_table("usuario")
    op.drop_table("restaurante")
    # ### end Alembic commands ###
