"""add foto_perfil_path and idade to usuario

Revision ID: d95df8627e2c
Revises: 6c3518848aff
Create Date: 2026-05-23 17:48:01.990447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95df8627e2c'
down_revision = '6c3518848aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('idade')
        batch_op.drop_column('foto_perfil_path')

    # ### end Alembic commands ###
